project_id = "wpadinulltmnllrsaimv"

[functions]
  [functions.auth-email-hook]
    verify_jwt = false
  [functions.exchange-rates]
    verify_jwt = false
  [functions.generate-blog-post]
    verify_jwt = false
  [functions.process-email-queue]
    verify_jwt = true
