project_id = "wpadinulltmnllrsaimv"

[functions]
  [functions.auth-email-hook]
    verify_jwt = false
  [functions.exchange-rates]
    verify_jwt = false
  [functions.generate-blog-post]
    verify_jwt = false
  [functions.process-email-queue]
    verify_jwt = true
  [functions.send-transactional-email]
    verify_jwt = true
  [functions.handle-email-unsubscribe]
    verify_jwt = false
  [functions.handle-email-suppression]
    verify_jwt = false
  [functions.send-weekly-heat-check]
    verify_jwt = true
