// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/search-products.ts
import { createClient } from "npm:@supabase/supabase-js@^2.108.2";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z } from "npm:zod@^4.4.3";
var search_products_default = defineTool({
  name: "search_products",
  title: "Search products",
  description: "Search DRIPWAY's scraped product catalog by keyword. Optionally filter by brand name. Returns products with name, brand, price, image, and affiliate URL.",
  inputSchema: {
    query: z.string().trim().min(1).describe("Keyword to match against product name or description."),
    brand_name: z.string().trim().optional().describe("Optional brand name filter (case-insensitive)."),
    limit: z.number().int().min(1).max(50).default(10).describe("Max results (1-50).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ query, brand_name, limit }) => {
    const supabase = createClient(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
      auth: { persistSession: false, autoRefreshToken: false }
    });
    let q = supabase.from("scraped_products").select("id, name, brand_name, brand_id, price, image, affiliate_url, category, description").or(`name.ilike.%${query}%,description.ilike.%${query}%`).limit(limit);
    if (brand_name) q = q.ilike("brand_name", `%${brand_name}%`);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { products: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-brands.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.108.2";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z2 } from "npm:zod@^4.4.3";
var list_brands_default = defineTool2({
  name: "list_brands",
  title: "List brands",
  description: "List distinct brands available in DRIPWAY's scraped product catalog, with product counts and a link to the brand page.",
  inputSchema: {
    limit: z2.number().int().min(1).max(200).default(50).describe("Max brands to return.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }) => {
    const supabase = createClient2(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
      auth: { persistSession: false, autoRefreshToken: false }
    });
    const { data, error } = await supabase.from("scraped_products").select("brand_id, brand_name").limit(2e3);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const counts = /* @__PURE__ */ new Map();
    for (const row of data ?? []) {
      const key = row.brand_id ?? row.brand_name;
      if (!key) continue;
      const existing = counts.get(key);
      if (existing) existing.count++;
      else counts.set(key, { brand_id: row.brand_id, brand_name: row.brand_name, count: 1 });
    }
    const brands = Array.from(counts.values()).sort((a, b) => b.count - a.count).slice(0, limit).map((b) => ({ ...b, url: `https://thedripway.com/brand/${b.brand_id ?? ""}` }));
    return {
      content: [{ type: "text", text: JSON.stringify(brands) }],
      structuredContent: { brands }
    };
  }
});

// src/lib/mcp/tools/list-blog-posts.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.108.2";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z3 } from "npm:zod@^4.4.3";
var list_blog_posts_default = defineTool3({
  name: "list_blog_posts",
  title: "List editorial posts",
  description: "List DRIPWAY editorial blog posts (title, slug, excerpt, category, date).",
  inputSchema: {
    limit: z3.number().int().min(1).max(50).default(10),
    category: z3.string().trim().optional().describe("Optional category filter.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit, category }) => {
    const supabase = createClient3(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
      auth: { persistSession: false, autoRefreshToken: false }
    });
    let q = supabase.from("blog_posts").select("title, slug, excerpt, category, author, read_time, created_at").eq("published", true).order("created_at", { ascending: false }).limit(limit);
    if (category) q = q.eq("category", category);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const posts = (data ?? []).map((p) => ({
      ...p,
      url: `https://thedripway.com/blog/${p.slug}`
    }));
    return {
      content: [{ type: "text", text: JSON.stringify(posts) }],
      structuredContent: { posts }
    };
  }
});

// src/lib/mcp/tools/get-blog-post.ts
import { createClient as createClient4 } from "npm:@supabase/supabase-js@^2.108.2";
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z4 } from "npm:zod@^4.4.3";
var get_blog_post_default = defineTool4({
  name: "get_blog_post",
  title: "Get editorial post",
  description: "Fetch the full content of a DRIPWAY editorial post by slug.",
  inputSchema: {
    slug: z4.string().trim().min(1).describe("Blog post slug from list_blog_posts.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ slug }) => {
    const supabase = createClient4(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
      auth: { persistSession: false, autoRefreshToken: false }
    });
    const { data, error } = await supabase.from("blog_posts").select("title, slug, excerpt, content, category, author, read_time, cover_image_url, created_at").eq("slug", slug).eq("published", true).maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!data) return { content: [{ type: "text", text: "Post not found" }], isError: true };
    const post = { ...data, url: `https://thedripway.com/blog/${data.slug}` };
    return {
      content: [{ type: "text", text: JSON.stringify(post) }],
      structuredContent: { post }
    };
  }
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "dripway-mcp",
  title: "DRIPWAY",
  version: "0.1.0",
  instructions: "DRIPWAY is a discovery engine for niche, emerging, and underground fashion brands. Use these tools to search products, browse brands, and read DRIPWAY's editorial posts. Shop links point to thedripway.com and its affiliate partners.",
  tools: [search_products_default, list_brands_default, list_blog_posts_default, get_blog_post_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
